### ISSUE TITLE
Android打release包，页面打开错误，错误码-1001 报错信息:degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1，之前只用weex没有问题

### ISSUE THREAD

**Issue by wangxiongtao** [kuaifan/eeui#111]

**Comment by kuaifan** [comment]
打包复现项目发我看看

**Comment by wangxiongtao** [comment]
我把安卓里面的混淆关了就好了，之前我把混淆打开就出这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kuaifan/eeui"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月22日(星期三) 中午11:48
收件人:&nbsp;"kuaifan/eeui"<eeui@noreply.github.com&gt;;
抄送:&nbsp;"晓梦千年"<1220577523@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kuaifan/eeui] Android打release包，页面打开错误，错误码-1001 报错信息:degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1，之前只用weex没有问题 (#111)





 
打包复现项目发我看看
