### ISSUE TITLE
tabbar 组件 iOS 版 未触发 viewCreated 事件

### ISSUE THREAD

**Issue by yyqqing** [kuaifan/eeui#113]
tabbar 组件 iOS 版 未触发 viewCreated 事件

**Comment by kuaifan** [comment]
建议使用最新的生命周期事件 https://eeui.app/guide/lifecycle.html

**Comment by yyqqing** [comment]
这并不一样。生命周期是在 tab 页面内部进行处理的，而 viewCreated 是要在 tabbar 所在页面即外部进行处理的。这个事件在需要处理首次进入 tab 某页面时很有用（比如记录某页面是否加载），如果用 生命周期 则必须配合跨页面通讯才行，这太麻烦了，且文档里已说明、android 已实现，建议 iOS 修复此bug

**Comment by kuaifan** [comment]
tabpage也支持生命周期所有事件的
