### ISSUE TITLE
How to reduce output (apk/ipa) size?

### ISSUE THREAD

**Issue by ukik** [kuaifan/eeui#134]
How to reduce .apk size? I think it is too big compared to original weex .apk

**Comment by jungledrum** [comment]
试试[appboard](https://eeui.app/guide/appboard.html)

**Comment by ukik** [comment]
I mean "Hello World" apk size
debug: 38,555 Kb (38,5 MB)
release: 34,673 Kb (34,6 MB)

I think this size so big, what should I do to reduce the original size?

**Comment by akFace** [comment]
delete x86 or other ndk 
![image](https://user-images.githubusercontent.com/22288837/125579180-c11ab5e4-9ea6-4091-9023-8b5712ce4d98.png)

**Comment by ukik** [comment]
`
λ gradlew buildRelease

> Configure project :app
WARNING:: DSL element 'annotationProcessorOptions.includeCompileClasspath' is obsolete.
It will be removed in version 7.0 of the Android Gradle plugin.
It does not do anything and AGP no longer includes annotation processors added on your project's compile classpath

> Configure project :eeui
WARNING:: DSL element 'annotationProcessorOptions.includeCompileClasspath' is obsolete.
It will be removed in version 7.0 of the Android Gradle plugin.
It does not do anything and AGP no longer includes annotation processors added on your project's compile classpath

> Configure project :weex_sdk
null
WARNING:: Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: root project 'eeuiApp', project ':app', project ':eeui', ...

> Task :weex_sdk:generateJsonModelRelease
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|armeabi-v7a : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\CMakeLists.txt:45:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|armeabi-v7a : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\CMakeLists.txt:45:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|armeabi-v7a : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\js_runtime\CMakeLists.txt:207:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|armeabi-v7a : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\js_runtime\CMakeLists.txt:207:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|arm64-v8a : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\CMakeLists.txt:45:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|arm64-v8a : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\CMakeLists.txt:45:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|arm64-v8a : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\js_runtime\CMakeLists.txt:207:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|arm64-v8a : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\js_runtime\CMakeLists.txt:207:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|x86 : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\CMakeLists.txt:45:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|x86 : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\CMakeLists.txt:45:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|x86 : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\js_runtime\CMakeLists.txt:207:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|x86 : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\js_runtime\CMakeLists.txt:207:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|x86_64 : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\CMakeLists.txt:45:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|x86_64 : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\CMakeLists.txt:45:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|x86_64 : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\js_runtime\CMakeLists.txt:207:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.
C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\CMakeLists.txt : C/C++ release|x86_64 : CMake Warning (dev) at C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\src\legacyRelease\cpp\Source\js_runtime\CMakeLists.txt:207:
  Syntax Warning in cmake code at column 31

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

> Task :weex_sdk:externalNativeBuildRelease
Build multiple targets weexcore_armeabi-v7a libweexjsb.so_armeabi-v7a weexjss_armeabi-v7a libweexjst.so_armeabi-v7a
ninja: Entering directory `C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\.cxx\cmake\release\armeabi-v7a'
Build multiple targets libweexjst.so_arm64-v8a weexcore_arm64-v8a weexjss_arm64-v8a libweexjsb.so_arm64-v8a
ninja: Entering directory `C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\.cxx\cmake\release\arm64-v8a'
Build multiple targets libweexjst.so_x86 libweexjsb.so_x86 weexjss_x86 weexcore_x86
ninja: Entering directory `C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\.cxx\cmake\release\x86'
Build multiple targets libweexjst.so_x86_64 weexcore_x86_64 weexjss_x86_64 libweexjsb.so_x86_64
ninja: Entering directory `C:\Users\ASUS\Desktop\eeui-demo\eeui-boilerplate-china-2.4\plugins\eeui\WeexSDK\android\sdk\.cxx\cmake\release\x86_64'

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

`

**Comment by ukik** [comment]
> delete x86 or other ndk
> ![image](https://user-images.githubusercontent.com/22288837/125579180-c11ab5e4-9ea6-4091-9023-8b5712ce4d98.png)

Thank you, it works
