### ISSUE TITLE
怎么设置首页状态栏的背景色

### ISSUE THREAD

**Issue by GH-A-Kai** [kuaifan/eeui#146]
跳转页面可以在openPage的时候配置，但是首页怎么配置，

**Comment by kuaifan** [comment]
看eeui.config.json配置文件

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 阿开 ***@***.***>
发送时间: Tuesday, September 20, 2022 2:38:56 PM
收件人: kuaifan/eeui ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kuaifan/eeui] 怎么设置首页状态栏的背景色 (Issue #146)


跳转页面可以在openPage的时候配置，但是首页怎么配置，

―

**Comment by GH-A-Kai** [comment]
> 看eeui.config.json配置文件 获取 Outlook for iOS<https://aka.ms/o0ukef>
<img width="536" alt="image" src="https://user-images.githubusercontent.com/63035134/191207513-28149855-976b-4641-9351-9072ac84cd24.png">
我之前配置过，不生效，只有android的导航栏上方会有一个高度，是我配置的不对吗？，可以给出详细一点配置不，感谢大佬
<img width="453" alt="image" src="https://user-images.githubusercontent.com/63035134/191208451-9d98b948-5da3-41b3-afa4-6230d0cc3677.png">
