### ISSUE TITLE
scroll-view能否添加类似header的子组件

### ISSUE THREAD

**Issue by kang558** [kuaifan/eeui#17]
[https://eeui.app/component/scroll-view.html](https://eeui.app/component/scroll-view.html)
能否添加类似
[weex的list](https://weex.apache.org/zh/docs/components/list.html#%E7%AE%80%E4%BB%8B)
header
当 header 到达屏幕顶部时，吸附在屏幕顶部。这个经常用到咦 :smiley:

**Comment by kuaifan** [comment]
也许你设置一个顶部漂浮view，然后监听scroll-view滚动到顶部时显示。

**Comment by kang558** [comment]
> 也许你设置一个顶部漂浮view，然后监听scroll-view滚动到顶部时显示。

这样做效果没那么好

**Comment by kuaifan** [comment]
研究研究

**Comment by kuaifan** [comment]
@kang558 1.0.2主程序版本已经支持，https://eeui.app/component/scroll-view.html#scroll-header
