### ISSUE TITLE
能不能eeui可以下载多个zip,每一个zip都是单独的weex应用，那样就可以进行业务定制化和隔离了。

### ISSUE THREAD

**Issue by sgnah** [kuaifan/eeui#19]
能不能eeui可以下载多个zip,每一个zip都是单独的weex应用，那样就可以进行业务定制化和隔离了。实现微信小程序引擎那样子。

**Comment by kang558** [comment]
小程序引擎啊，这可不是一般额复杂

**Comment by kuaifan** [comment]
很不错的建议。可惜目前没有，计划增加的功能。

weex eeui 文档：[https://eeui.app/](https://eeui.app/)
weex eeui 插件大全：[https://eeui.app/markets/](https://eeui.app/markets/)
weex eeui 中文交流社区：[https://bbs.eeui.app/](https://bbs.eeui.app/)
