### ISSUE TITLE
建议在eeui加上灵活设置本地首页，目前的本地首页只能设置为空

### ISSUE THREAD

**Issue by zhijijason** [kuaifan/eeui#20]
配置相关：[https://eeui.app/guide/config.html#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6](https://eeui.app/guide/config.html#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)

配置项参数homePage，希望可以设置本地js文件，且任意名称

![image](https://user-images.githubusercontent.com/22288837/63415287-161d3d00-c430-11e9-8d89-ef91ffb7778b.png)

**Comment by kuaifan** [comment]
已加入下个版本计划，感谢对eeui的支持。

weex eeui 文档：[https://eeui.app/](https://eeui.app/)
weex eeui 插件大全：[https://eeui.app/markets/](https://eeui.app/markets/)
weex eeui 中文交流社区：[https://bbs.eeui.app/](https://bbs.eeui.app/)

**Comment by kuaifan** [comment]
[1.0.10](https://github.com/kuaifan/eeui/releases/tag/1.0.10) 已支持此功能，感谢对eeui的支持。

weex eeui 文档：[https://eeui.app/](https://eeui.app/)
weex eeui 插件大全：[https://eeui.app/markets/](https://eeui.app/markets/)
weex eeui 中文交流社区：[https://bbs.eeui.app/](https://bbs.eeui.app/)
