### ISSUE TITLE
建议eeui加上动态设置默认首页功能

### ISSUE THREAD

**Issue by zhijijason** [kuaifan/eeui#21]
#### 建议eeui加上动态设置默认首页功能，
为什么要加上这个功能呢：
比方说我退出登陆从首页跳到登陆后，就把app关了，按照一般思维来说，再打开app的时候，应该要打开登陆的页面，但是按照eeui这个框架来讲，会先打开index首页，我知道可以通过v-if来判断之类的，但是这样的话，会导致页面会一闪然后再跳到登陆页面，这样给用户的体验不好，要是eeui能加个动态设置默认首页功能，那时用户退出到登陆页面的时候，我就调用setHomePage动态设置默认首页，然后用户再打开APP的时候，就会直接跳到登陆页面，无需跳来跳去的

**Comment by kang558** [comment]
@kuaifan  大概思路可以这样做:
根据传过来的值，生成缓存值，然后发出通知让首页重新加载内容，再次登陆的时候，若缓存有值，则采用缓存的值，不采用config.json的值 :smiley:

**Comment by kuaifan** [comment]
[1.0.10](https://github.com/kuaifan/eeui/releases/tag/1.0.10) 已支持此功能，感谢对eeui的支持。

weex eeui 文档：[https://eeui.app/](https://eeui.app/)
weex eeui 插件大全：[https://eeui.app/markets/](https://eeui.app/markets/)
weex eeui 中文交流社区：[https://bbs.eeui.app/](https://bbs.eeui.app/)
