### ISSUE TITLE
大佬，weex的video能支持全屏么？

### ISSUE THREAD

**Issue by KaelInvoker** [kuaifan/eeui#23]
如题..另外，还想问句，插件的源码在哪？

**Comment by KaelInvoker** [comment]
还有个问题，大佬项目能不能托管到码云上啊，这里下载实在太慢了

**Comment by kang558** [comment]
视频有eeui插件的啊 
[https://eeui.app/markets/detail.html#videoView](https://eeui.app/markets/detail.html#videoView)

**Comment by kuaifan** [comment]
> 视频有eeui插件的啊
> https://eeui.app/markets/detail.html#videoView

这个插件支持全屏的，码云下载需要验证码，不合适啊

**Comment by kang558** [comment]
clone 不需要验证码啊，下载zip才需要 @kuaifan

**Comment by KaelInvoker** [comment]
这个插件大佬在线上项目使用了么?没有问题吧

**Comment by kuaifan** [comment]
> clone 不需要验证码啊，下载zip才需要 @kuaifan

就是要下载zip，eeui走curl不走clone，git不一定每个人都装

**Comment by kang558** [comment]
> 这个插件大佬在线上项目使用了么?没有问题吧

你自己试试咯

**Comment by kang558** [comment]
> > clone 不需要验证码啊，下载zip才需要 @kuaifan
> 
> 就是要下载zip，eeui走curl不走clone，git不一定每个人都装

那就算咯
