### ISSUE TITLE
BUG反馈：在wifi同步下，openPage到另一个页面，当内容有变动时会导致顶部导航栏消失

### ISSUE THREAD

**Issue by zhijijason** [kuaifan/eeui#24]
操作系统是安卓6.0，在wifi同步下，openPage到另一个页面，openPage代码如下：
eeui.openPage({
                    url: 'test.js',
                    pageName: 'test',
                    pageType: 'app',
                    animatedType: 'push',
                    pageTitle:'测试',
                    softInputMode: 'pan'
                });
test.vue没有使用navbar设置顶部导航栏，openPage到test.vue时，有默认的顶部导航栏出现，但改动内容后，在wifi同步下会导致顶部导航栏消失！

**Comment by kuaifan** [comment]
尝试过别的机型或者重启app吗？android部分机型的导航栏系统会干涉的。
如果仍需要进一步跟进，希望可以提供录屏复现效果。

**Comment by zhijijason** [comment]
小米、乐视手机两个机型测试过了，都有这个问题，以下是录屏效果，因为不支持mp4上传，我打包成zip文件上传：
[录屏复现效果效果.mp4.zip](https://github.com/kuaifan/eeui/files/3549445/mp4.zip)

**Comment by zhijijason** [comment]
> 尝试过别的机型或者重启app吗？android部分机型的导航栏系统会干涉的。
> 如果仍需要进一步跟进，希望可以提供录屏复现效果。

小米、乐视手机两个机型测试过了，都有这个问题，以下是录屏效果，因为不支持mp4上传，我打包成zip文件上传：
[录屏复现效果效果.mp4.zip](https://github.com/kuaifan/eeui/files/3549445/mp4.zip)

**Comment by zhijijason** [comment]
@kuaifan 小米、乐视手机两个机型测试过了，都有这个问题，以下是录屏效果，因为不支持mp4上传，我打包成zip文件上传：
录屏复现效果效果.mp4.zip

**Comment by kuaifan** [comment]
[1.0.11](https://github.com/kuaifan/eeui/releases/tag/1.0.11) 已修复。

weex eeui 文档：[https://eeui.app/](https://eeui.app/)
weex eeui 插件大全：[https://eeui.app/markets/](https://eeui.app/markets/)
weex eeui 中文交流社区：[https://bbs.eeui.app/](https://bbs.eeui.app/)
