### ISSUE TITLE
建议开发一个微信、QQ、微博等第三方登陆插件

### ISSUE THREAD

**Issue by zhijijason** [kuaifan/eeui#25]
建议开发一个微信、QQ、微博第三方登陆插件，这种功能太常用了

**Comment by kuaifan** [comment]
已加入计划，感谢支持。

weex eeui 文档：[https://eeui.app/](https://eeui.app/)
weex eeui 插件大全：[https://eeui.app/markets/](https://eeui.app/markets/)
weex eeui 中文交流社区：[https://bbs.eeui.app/](https://bbs.eeui.app/)
