### ISSUE TITLE
混合开发情况下原生调用 eeui 会出现中间跳转的空白页，就是等待页面

### ISSUE THREAD

**Issue by jankuo** [kuaifan/eeui#27]
混合开发情况下原生调用 eeui 会一闪而过中间跳转的等待页，我是哪里做错了吗

1. 原生代码 MainActivity
	
```java
        Intent intent = new Intent();
	intent.setAction(Intent.ACTION_VIEW);
	Uri uri = Uri.parse("demo://demo/");
	intent.setData(uri);
	startActivity(intent);
```

2.  WelcomeActivity 代码没变

3.  AndroidManifest.xml 

        <activity
            android:name="app.eeui.playground.WelcomeActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait"
            android:theme="@style/WelcomeStyle">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="xxdemo"
                    android:host="xxdemo" />
            </intent-filter>
        </activity>
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

**Comment by kuaifan** [comment]
能否录制下效果参考一下，如果在这里不方便发送视频或者图片你可以发到我的邮箱aipaw@qq.com。
