### ISSUE TITLE
EEUI的IOS版的NSLog问题

### ISSUE THREAD

**Issue by zhijijason** [kuaifan/eeui#29]
EEUI原生代码很多地方是直接使用NSLog的输出还是比较消耗系统资源的，一般在release下是不用的，建议采用weex的WXLogInfo或自己定义一个宏比较好，比如：
#ifdef DEBUG
#define ZJLog(...) NSLog(__VA_ARGS__)
#else
#define ZJLog(...)
#endif

**Comment by kuaifan** [comment]
1.0.15版本已支持，建议更新至最新版本 https://github.com/kuaifan/eeui/releases/tag/1.0.15
