### ISSUE TITLE
建议在热更新的应用版本那里可添加多个需要热更新的版本号

### ISSUE THREAD

**Issue by zhijijason** [kuaifan/eeui#30]
比方说我有个1.1的热更新版本，要求1.0、1.0.1、1.0.2、1.0.3等版本都要进行热更新修复BUG，我只需在界面上的应用版本那里填写1;1.0.1;1.0.2;1.0.3即可，不用分别添加四条热更新记录，这样就方便多了，如图：
![image](https://user-images.githubusercontent.com/7219147/65292473-2db02880-db8a-11e9-9af4-2aedbfa1ca92.png)

**Comment by kuaifan** [comment]
[1.0.16](https://github.com/kuaifan/eeui-template/releases/tag/1.0.16) 已添加
