### ISSUE TITLE
希望能够添加个多语言支持方案。

### ISSUE THREAD

**Issue by LingCn** [kuaifan/eeui#34]
大佬，希望能够添加个多语言支持方案。

**Comment by kuaifan** [comment]
EEUI Online Editor 官方模板例子新增了一个国际化的版本，可以参考一下。

https://editor.eeui.app/#/files/eeui/official/tree/3d888453570367d6173bdc4397b52496/src/pages/index.vue

**Comment by LingCn** [comment]
好的，谢谢
