### ISSUE TITLE
建议拓展eeui.reloadPage的功能

### ISSUE THREAD

**Issue by zhijijason** [kuaifan/eeui#37]
目前reloadPage这个方法只能刷新页面，但是别的属性改变不了，比如要改变背景颜色，当然也可以通过weex页面来设置，但在iPhoneX下的底部会出现空白，当然上面只是打个比方，所以建议根据openPage的属性来拓展，这样reloadPage的通用性就比较大了

**Comment by kuaifan** [comment]
有些属性在构建页面之前已经初始化，然后刷新属于构建之后的事件。建议使用打开新页面然后关闭当前页面的形式实现。
