### ISSUE TITLE
建议添加支持pug

### ISSUE THREAD

**Issue by pecopeco** [kuaifan/eeui#39]
求支持引入pug模板引擎，写原生html痛不欲生

在weex中无需任何配置可以直接使用pug，按理做了上层封装的eeui应该可以使用才对

抓光了头发的情况下已找到解决方法：

进入c:/user/xxx/AppData/Roaming/npm/node_modules/eeui-cli，在eeui脚手架中自行安装pug：

`npm i pug`

**Comment by kang558** [comment]
npm install less less-loader --save
<style scoped lang="less"></style>

**Comment by pecopeco** [comment]
> ```
> 1、安装 npm install less less-loader --save
> 
> 2、使用
> <style scoped lang="less">
> </style>
> ```
> 
> #### 注：weex不支持嵌套写法
> ```css
> 错误写法
> .box{
>   background-color: pink;
>   .a {
>     color: red;
>  }
> }
> ```
> 
> ```css
> 正确写法
> .box{
>   background-color: pink;
> }
> .a {
>     color: red;
>  }
> ```

请问如何引入 pug ？

**Comment by kang558** [comment]
没用过pug  :smile:

**Comment by neterji** [comment]
> ```
> ```
> 1、安装 npm install less less-loader --save
> 
> 2、使用
> <style scoped lang="less">
> </style>
> ```
> 
> 
> 注：weex不支持嵌套写法
> ```css
> 错误写法
> .box{
>   background-color: pink;
>   .a {
>     color: red;
>  }
> }
> ```
> 
> 
> ```css
> 正确写法
> .box{
>   background-color: pink;
> }
> .a {
>     color: red;
>  }
> ```
> ```

那和直接写css有啥区别？

**Comment by kang558** [comment]
@neterji 可以用来做公共类、公共样式

**Comment by pecopeco** [comment]
自己修改 webpack.config.js 添加 rules会报错
`Error: Rule can only have one result source (provided use and loader) in {
  "test": {},
  "use": [
    {
      "loader": "babel-loader",
      "options": {
        "presets": [
          "@babel/react",
          "@babel/env"
        ],
        "plugins": [
          [
            "@babel/transform-runtime",
            {
              "helpers": false
            }
          ],
          [
            "component",
            {
              "libraryName": "weex-ui",
              "libDir": "packages",
              "style": false
            },
            "weex-ui"
          ],
          [
            "component",
            {
              "libraryName": "eeui-design",
              "libDir": "packages",
              "style": false
            },
            "eeui-design"
          ]
        ]
      }
    }
  ],
  "loader": "pug--plain-loader"
}`

**Comment by monkey01127** [comment]
你好，最后引入Pug成功了么？

**Comment by pecopeco** [comment]
> eeui 如何引入Pug，能否给出大致的方式呀？

我在上面已经说得很清楚了吧，安装完就可以直接用，不用引入
