### ISSUE TITLE
weex-ui无法按需引入

### ISSUE THREAD

**Issue by kang558** [kuaifan/eeui#42]
#### 按照这个步骤来配置，执行npm run dev 报错 ，[weex-ui](https://weex-ui-team.github.io/weex-ui/#/cn/?id=%e4%bd%bf%e7%94%a8%e5%89%8d)
![image](https://user-images.githubusercontent.com/22288837/69321927-eaa02d80-0c7e-11ea-9934-e7d42c4098e8.png)
#### 不按需引入weex-ui打出来的js包实在太大了，每个文件1.4M左右

**Comment by kang558** [comment]
配置问题，解决了
1、安装babel插件： npm i babel-preset-stage-0 babel-plugin-component  -D
2、安装weex-ui和weex-amui： npm i weex-ui -S 和 npm i weex-amui -S
3、在 .babelrc 文件中添加
```js
{
    "presets": [
        "es2015",
        "stage-0"
    ],
    "plugins": [
        [
            "component",
            {
            "libraryName": "weex-amui",
            "libDir": "packages",
            "style": false
            }
            // 如果要和 weex-ui 一起用，配置加上下面这个
            ,{
            "libraryName": "weex-ui",
            "libDir": "packages",
            "style": false
            }
        ],
        ["transform-runtime", {
            "polyfill": false,
            "helpers": false
        }]
    ]
}

```

**Comment by kang558** [comment]
#### 就weex-amui按需起作用
#### weex-ui不行,还是很大，虽然不报错了，只引入了button，打包出来还带有其他的

![image](https://user-images.githubusercontent.com/22288837/69406230-8b085780-0d3c-11ea-97b5-8907206dbcaa.png)

**Comment by HOWAREYOUIAMFINE** [comment]
要同时做到weex-ui和weex-amui按需引入，你需要修改 .babelrc文件如下：
```javascript
{
    "presets": [
        "es2015",
        "stage-0"
    ],
    "plugins": [
        [
            "component",
            [
                {
                    "libraryName": "weex-amui",
                    "libDir": "packages",
                    "style": false
                },
                {
                    "libraryName": "weex-ui",
                    "libDir": "packages",
                    "style": false
                }
            ]
        ],
        [
            "transform-runtime",
            {
                "helpers": false,
                "polyfill": false
            }
        ]
    ]
}
```
这可能是因为“babel-pugin-component”的官方配置错误引起的，请看这个：
[同时按需引入两个组件，官方的配置报错，如何配置](https://github.com/ElementUI/babel-plugin-component/issues/54#issuecomment-522895139)
使用eeui Demo项目在windows和mac环境下实测，均是可以做到weex-ui和weex-amui按需引入的：
![image](https://user-images.githubusercontent.com/58383049/69911219-52126600-1453-11ea-8b9f-0579b6663668.png)

![image](https://user-images.githubusercontent.com/58383049/69911226-5fc7eb80-1453-11ea-8e1e-03946e9f05b3.png)

实际build出来的JS文件只有37kb左右
![image](https://user-images.githubusercontent.com/58383049/69911245-9867c500-1453-11ea-92ae-cc93f6e2d196.png)

**Comment by kang558** [comment]
感觉是我的环境问题
