### ISSUE TITLE
用一个页面载入两个图表会显示同样的数据

### ISSUE THREAD

**Issue by kang558** [kuaifan/eeui#44]
目前我的解决方案用的setTimeout，即等待第一个渲染完之后再渲染第二个，这样做就不会显示同样的图表，[加了setTimeout在线示例](https://editor.eeui.app/#/files/kang/offcoal-demo/src/pages/ui_echarts_demo.vue)，如果去掉setTimeout就会显示同样的数据图表
如果同一个页面有很多个的时候就不好处理了

**Comment by kuaifan** [comment]
已修复，可以实现2个或多个数据图表同事显示，详情请参考[多个图表在线演示代码](https://editor.eeui.app/#/files/eeui/official/tree/a1133cf10fe4e8490845c465b1e08d39/src/pages/ui_echarts_demo_many.vue)。
