### ISSUE TITLE
【BUG】安卓APP打包后图片位置异常

### ISSUE THREAD

**Issue by netzhouxiang** [kuaifan/eeui#47]
![image](https://user-images.githubusercontent.com/20832795/70039307-aa349e00-15f4-11ea-8c23-4a579e829e91.png)
![QQ图片20191203174602](https://user-images.githubusercontent.com/20832795/70039375-ca645d00-15f4-11ea-993a-c697340f621a.jpg)

**Comment by kuaifan** [comment]
感谢你的支持，你的问题我们测试无法复现，希望你可以将演示代码放到 https://editor.eeui.app/ 以方便我们修复问题。

**Comment by netzhouxiang** [comment]
问题已经解决
