### ISSUE TITLE
建议在eeui.saveImage 保存图片的时候可以自行添加文件命

### ISSUE THREAD

**Issue by Carson-czl** [kuaifan/eeui#48]
- 
![6950ab4d20d42efc37f8203d55fdab9](https://user-images.githubusercontent.com/36708623/70240858-f0326300-17a8-11ea-80ae-21892dc85ffb.jpg)
希望能够开发自行可以写入文件命名类似这样写
![1c320edaf1fd5f323ca0d479b1bbcb5](https://user-images.githubusercontent.com/36708623/70240938-1b1cb700-17a9-11ea-85a9-d2893fe1eb1c.png)

**Comment by kuaifan** [comment]
不错的建议

**Comment by kuaifan** [comment]
1.0.34 已新增方法，详情： https://github.com/kuaifan/eeui-template/releases/tag/1.0.34
