### ISSUE TITLE
建议 eeui.openOtherApp方法，增加 scheme参数

### ISSUE THREAD

**Issue by Sgenmi** [kuaifan/eeui#49]
eeui组件有一个eeui.openOtherApp方法，是否可以增加一个参数scheme:true/false ,默认false,就是现在的功能，当是true时，可以自己写type的值[可以是其他APP的scheme]

**Comment by kuaifan** [comment]
1.0.34 已新增方法，详情： https://github.com/kuaifan/eeui-template/releases/tag/1.0.34
