### ISSUE TITLE
安卓下tabbar + scroll-view + input 输入法弹窗的时候会出现页面渲染错误

### ISSUE THREAD

**Issue by mrz9** [kuaifan/eeui#51]
eeui-cli 1.0.33
eeui-template 1.0.33
测试设备 Android 9 (ios正常）

选择input框的时候出现
![image](https://user-images.githubusercontent.com/5961216/70592862-b2e92d80-1c0d-11ea-9af1-482cfcef71af.png)
![image](https://user-images.githubusercontent.com/5961216/70592875-ba103b80-1c0d-11ea-81ba-994f71fc4b1f.png)

**Comment by kuaifan** [comment]
`swipeColorBack`写成`false`就可以了，
```
eeui.openPage({
    swipeColorBack: false,
    ......
})
```

**Comment by crobotvip** [comment]
indexpage 出现这个问题可以通过修改 WelcomeActivity的openNext方法
`mPageBean.setSwipeColorBack(eeuiParse.parseBool(eeuiBase.config.getHomeParams("swipeColorBack", "false")));//把默认值true修改为false`
