### ISSUE TITLE
tabbar 在安卓中默认选中时，未加粗

### ISSUE THREAD

**Issue by Sgenmi** [kuaifan/eeui#52]
开发调试：Redmi note 7 pro

bug:在设置默认选中时，字体设置了加粗，未达到效果 【滚动一下，会加粗】
![QQ20191212-0](https://user-images.githubusercontent.com/3337501/70674270-70ccf400-1cc0-11ea-916f-1183295a7203.png)

**Comment by kuaifan** [comment]
1.0.34 已修复 https://github.com/kuaifan/eeui-template/releases/tag/1.0.34
