### ISSUE TITLE
image 组件在eeui 好像有bug

### ISSUE THREAD

**Issue by Sgenmi** [kuaifan/eeui#54]
获取不到 naturaWidth,naturaHeight
eeui中，代码：https://editor.eeui.app/#/files/Sgenmi/tts/src/pages/img.vue
如下图：
![WechatIMG5](https://user-images.githubusercontent.com/3337501/70768423-02f7f980-1da0-11ea-8cf7-16014c603c52.jpeg)

### **注：官方的用 weex Playground 是正常的，如下图：**
![WechatIMG6](https://user-images.githubusercontent.com/3337501/70768441-1b681400-1da0-11ea-8958-63052eb97db8.jpeg)

**Comment by kuaifan** [comment]
图片适配器ImageAdapter的问题，选用picasso就可以了。具体方法请查看[eeui.config.js](https://eeui.app/guide/config.html#android-%E5%AE%89%E5%8D%93%E7%AB%AF%E7%9B%B8%E5%85%B3%E9%85%8D%E7%BD%AE)配置。
