### ISSUE TITLE
eeui.toast 字体太大，随便几个字就要换行了

### ISSUE THREAD

**Issue by Sgenmi** [kuaifan/eeui#55]
eeui.toast 字体太大，随便几个字就要换行了 如：
 eeui.toast({
    message:'在一次返回退出随风行app',
    gravity:'bottom'
})
 直接换行了。

**希望：能设置字体大小**

**Comment by kuaifan** [comment]
用的是系统的toast，应该是跟系统字体大小有关系的

**Comment by Sgenmi** [comment]
@kuaifan 是否可以增加一个字体大小参数，如果为空，则默认系统，否则为所填字体大小
