### ISSUE TITLE
tabbar iphone下，有滚动条出现

### ISSUE THREAD

**Issue by Sgenmi** [kuaifan/eeui#57]
在Iphone下滚动时，有滚动条出现。 【android 没有】

希望: 不出现滚动条 或者 可以设置出现或不出现
![D6952E9E-3907-4FA3-9B9A-37066E48AB85](https://user-images.githubusercontent.com/3337501/71323480-ac608d00-250e-11ea-958b-ef9641dab5da.png)

**Comment by kuaifan** [comment]
1.0.39已修复。
