### ISSUE TITLE
tabbar 未选中与选中同色时，不加粗 bug

### ISSUE THREAD

**Issue by Sgenmi** [kuaifan/eeui#59]
Android：
     tabbar 未选中与选中同色时，设置了字体加粗  ，但是效果是没有加粗
Ios: 正常

demo: https://editor.eeui.app/#/files/Sgenmi/tts/src/pages/homeTab.vue

希望结果： 同色时，希望能加粗，如果选中能设置字体大小就更好了。

额外希望结果：开启  "loading":true, 时，希望加载图标的背景可以自定义或透明色。 这样做的主要目的解决 app页面自义了背景色，和加载图标的背景不一样时，会出现一次闪屏的情况 【背景色相互替换导致】。

**Comment by kuaifan** [comment]
1.0.39已修复。
