### ISSUE TITLE
迁移lottie插件

### ISSUE THREAD

**Issue by kang558** [kuaifan/eeui#60]
#### 目前weex有[weexplus](https://weexplus.github.io/doc/plugin/lottie.html)版本，希望能迁移过来，[GitHub](https://github.com/farwolf2010/lottie)

Lottie是Airbnb开源的一个支持 Android、iOS 以及 ReactNative，利用json文件的方式快速实现动画效果的库。

#### 相当多的动画资源 : [https://lottiefiles.com/popular](https://lottiefiles.com/popular) 这个动画库真的很牛皮
Lottie官方项目地址：[https://github.com/airbnb/lottie](https://github.com/airbnb/lottie)

**Comment by kang558** [comment]
我尝试了安卓版本[【下载 Android-lottie.zip】](https://github.com/kuaifan/eeui/files/4006986/lottie.zip)，但是一直闪退，不知所云 :joy:

**Comment by kuaifan** [comment]
https://eeui.app/markets/eeui/lottie

**Comment by kang558** [comment]
> https://eeui.app/markets/eeui/lottie

牛皮！
