### ISSUE TITLE
建议 tabbar 中参数 indicator 可以设置Margin

### ISSUE THREAD

**Issue by Sgenmi** [kuaifan/eeui#61]
建议 tabbar 中参数 indicator 可以设置Margin  ，也就是indicator离文字的距离，现在不管tabbar多高，都在底边处 
![B6382028-7073-416E-BAEB-B1E38ECDDC05](https://user-images.githubusercontent.com/3337501/71545170-d4df0000-29c2-11ea-97d8-ee1c0465029f.png)

希望结果：可以设置indicatorMargin ，这样不用一直在底边，
![97FB99B2-AE50-4BE5-9DB2-930B42A3C24B](https://user-images.githubusercontent.com/3337501/71545172-e0322b80-29c2-11ea-9cbd-e99687d0fcde.png)

**Comment by kuaifan** [comment]
tabbar 建议[完全自定义tabbar](https://eeui.app/component/tabbar.html#%E6%8B%93%E5%B1%95-%E5%AE%8C%E5%85%A8%E8%87%AA%E5%AE%9A%E4%B9%89tabbar)

**Comment by Sgenmi** [comment]
@kuaifan 大于10选项 这个自定义的，要做的东西就多了，tabbar跟陏滚动，indicator滚动，回弹，等一堆事件，相当于把原生里的代码效果重写一变。 我在研究研究。
