### ISSUE TITLE
tabbar 快速滑动时iphone 选中延时比较严重

### ISSUE THREAD

**Issue by Sgenmi** [kuaifan/eeui#63]
机型：iphone6 plus
demo:  https://editor.eeui.app/#/files/Sgenmi/tts/src/pages/navTab/home.vue
bug:当前快速滑动时，tabbar 都不会有选中的效果。最后都可能不会滚动到位置

注：android 正常

**Comment by kuaifan** [comment]
① ios的机制是滑动结束之后更新tab选择器，所以你快速滑动的时候是没有结束滑动的，只有你停止的时候才会选中你最后停留的选择器。
② 你说的”最后都可能不会滚动到位置“经过测试没有出现过，如果你可以测试出现请将复现的操作方法告知。
