### ISSUE TITLE
 eeui.setStatusBarStyle 在android下白屏

### ISSUE THREAD

**Issue by Sgenmi** [kuaifan/eeui#65]
机型：红米note 7 pro
系统：Android 9
demo:  [https://editor.eeui.app/#/files/Sgenmi/tts/src/pages/bug/setBarcolor.vue](https://editor.eeui.app/#/files/Sgenmi/tts/src/pages/bug/setBarcolor.vue)

 bug: **android 下白屏** 

 注：iphone 功能正常

**Comment by kuaifan** [comment]
没看出效果，你可以尝试图你的效果录制放上来

**Comment by Sgenmi** [comment]
@kuaifan  
![2020-01-08 10_18_16](https://user-images.githubusercontent.com/3337501/71945012-8a4e5680-3200-11ea-9c94-a190c73dd4d1.gif)

**Comment by kuaifan** [comment]
最新版已修复
