### ISSUE TITLE
iOS eeuiNewPageManager 的 closePageTo 的方法有问题，一边遍历数组一边删除数组元素，这样会导致删除后再通过i++获取的已经不是数组下一元素。

### ISSUE THREAD

**Issue by lisj168** [kuaifan/eeui#66]
iOS eeuiNewPageManager 的 closePageTo 的方法有问题，一边遍历数组一边删除数组元素，这样会导致删除后再通过i++获取的已经不是数组下一元素。
![image](https://user-images.githubusercontent.com/15119013/72244027-5a4fea80-3628-11ea-8746-d4f46e7db498.png)

**Comment by kuaifan** [comment]
2.2.0 已经修复
