### ISSUE TITLE
【BUG】热更新路径问题

### ISSUE THREAD

**Issue by netzhouxiang** [kuaifan/eeui#67]
问题描述：
index.vue 使用tabbar组件，组件内含有4个导航，其中一个导航URL：cart.js?statusBarType=immersion，在使用热更新重启后，index.vue页面获取的cart.js文件还是本地assets的；并没有读取热更新包路径，导致该热更新包更新后，其他文件已正常读取，该文件一直都是读取本地，无法更新；

问题处理结果：
去掉 ?statusBarType=immersion 正常

**Comment by kuaifan** [comment]
2.2.0版本已修复此问题
