### ISSUE TITLE
【BUG】热更新机制问题

### ISSUE THREAD

**Issue by netzhouxiang** [kuaifan/eeui#68]
当前热更新，不能单独更新某个vue（js）文件；会导致问题如下：

1、如果更新某个JS文件，那么该文件里使用都图片均需要更新，不然会出现页面没有图片问题；因为eeui在读取热更新包数据路径后，图片也相对读取了；所以现在都问题是不管这个vue有没有修改图片，如果更新；必须把图片带上。

2、热更新多次覆盖，最后一个包，必须带上上一次更新的js和图片；否则会出现更新丢失都情况

所以现在热更新好像只适用，dist整包更新

**Comment by kuaifan** [comment]
测试未发现，可以试一下新版本，如果还是有此问题请提供一下vue文件测试

**Comment by netzhouxiang** [comment]
https://github.com/kuaifan/eeui/issues/67 同该问题 已修复
