### ISSUE TITLE
【BUG】热更新ImageAdapter问题

### ISSUE THREAD

**Issue by netzhouxiang** [kuaifan/eeui#69]
问题描述：
我debug模式下，日志输出：
![QQ图片20200114112230](https://user-images.githubusercontent.com/20832795/72311604-317b3400-36c0-11ea-8e0d-426b58b4c24e.png)
然后在ImageAdapter挂断点，拿到的是这个：
![QQ图片20200114112310](https://user-images.githubusercontent.com/20832795/72311632-4952b800-36c0-11ea-9212-735e347102ef.png)

然后会通过这个代码：
![微信截图_20200114112355](https://user-images.githubusercontent.com/20832795/72311680-6b4c3a80-36c0-11ea-845c-72b5e70bcd5e.png)
把路径：
file:///storage/emulated/0/Android/data/app.pb.shop/files/update/http:--2-2f-f----2-2f-f--res.piercebarathea.com--2-2f-f--app--2-2f-f--zip--2-2f-f--1578969263251828966/images/share
变成：
file://assets/storage/emulated/0/Android/data/app.pb.shop/files/update/http:--2-2f-f----2-2f-f--res.piercebarathea.com--2-2f-f--app--2-2f-f--zip--2-2f-f--1578969263251828966/images/share

**Comment by netzhouxiang** [comment]
图片是使用的动态路径，如：<image :src="icon_img" />

**Comment by netzhouxiang** [comment]
:src="icon_img"

**Comment by kuaifan** [comment]
新版本测试未发现此问题，如还需要请提供vue代码测试。
