### ISSUE TITLE
在安卓4.4下，若statusBarType设为immersion，底部会出现空白

### ISSUE THREAD

**Issue by zhijijason** [kuaifan/eeui#70]
![image](https://user-images.githubusercontent.com/7219147/72711933-0b183580-3ba5-11ea-8448-e2300228dbb2.png)
代码网址如下：https://editor.eeui.app/#/files/zhijijason/test2/src/pages/index.vue

**Comment by kuaifan** [comment]
安卓5以下不建议使用跟透明有关的东西。
