### ISSUE TITLE
video-view插件，自动播放报错，点击播放按钮闪退

### ISSUE THREAD

**Issue by mrz9** [kuaifan/eeui#75]
![image](https://user-images.githubusercontent.com/5961216/74702273-1316d400-523c-11ea-8bba-53c05179fd40.png)

测试环境： nokia x7 android 9.0

[demo地址](https://editor.eeui.app/#/files/mrz9/video-demo/src/pages/index.vue)

**Comment by kuaifan** [comment]
已经发布新版本 https://eeui.app/markets/eeui/video

**Comment by kuaifan** [comment]
2.2.0 已经修复
