### ISSUE TITLE
是否把src目录里的app.eeui.playground改成在生成工程时指定的应用ID（如com.xxx.yyy)

### ISSUE THREAD

**Issue by neterji** [kuaifan/eeui#76]
在有些项目需要对包名进行验证，这时候系统固定的app.eeui.playground就不适合了，需要改成相应报名，但是在升级eeui的时候，有会生成原来的包，比较麻烦，希望改一下

**Comment by kuaifan** [comment]
2.2.0版本已经把app.eeui.playground改成在生成工程或使用eeui setting设置项目时的应用ID
