### ISSUE TITLE
eeui/audio部分机型获取音频时长错误，播放音频手机卡死

### ISSUE THREAD

**Issue by zkw1993** [kuaifan/eeui#78]
引入eeui/audio插件，音频测试地址是：http://47.103.83.40:8888/media/sound_recordings/1581994835243.wav；

在三星SM-G9209测试机上，调用获取音频时长与播放音频都可正常使用，
用小米MIX2型号的测试机上出现了获取音频时长不准确，播放音频程序卡死的状况

**Comment by kuaifan** [comment]
参考一下例子https://editor.eeui.app/#/files/eeui/music-player/src/pages/index.vue，如果也出现此问题请再说明。
