### ISSUE TITLE
eeui.closePage(); 会导致安卓端APP 异常退出

### ISSUE THREAD

**Issue by aqaun** [kuaifan/eeui#82]
登录页，登录后 通过 eeui.openPage 方法 进入到 主页面，主页通过tabbar 组件，加载三个 子页面（A，B，C），默认加载第一个页面A，切换到页面C 选择，退出登录 使用的方法是 eeui.closePage();。 此时APP正常跳转到登录页，然后我重复以上动作，从页面C 退出登录，然后APP 异常退出。

**Comment by kuaifan** [comment]
2.2.3已修复。
