### ISSUE TITLE
EEUI CLI 2.2.3 node_module 不传转成ES5

### ISSUE THREAD

**Issue by feishu** [kuaifan/eeui#87]
EEUI CLI 2.2.3 node_module 不传转成ES5
导致在 不支持ES6 的手机上全部报错

**Comment by kuaifan** [comment]
可以尝试修改`.babelrc`文件相关设置babel

**Comment by Fever325** [comment]
使用babel.config.js进行配置

**Comment by feishu** [comment]
也在.babelrc 下面配置了babel 了页面都会被转就是node_module 不会，有想应的例子吗难道我用的插件与大家的不一样

**Comment by Fever325** [comment]
我可能没给你说全，用babel.config.js 替代 .babelrc  在babel.config.js 里 使用 module.exports = {}，导出配置，你直接把.babelrc里的复制过来就行，都是一样的配置，只不过换了种文件形式而已。这样就可以把node_modules里的模块转成es5了

**Comment by Fever325** [comment]
具体细节问题可以去看babel官网，里面有讲.babelrc和babel.config.js的区别

**Comment by kuaifan** [comment]
2.3.0+已经支持

**Comment by feishu** [comment]
但是发现 dev的时候代码还是没转成es5

**Comment by kang558** [comment]
目前最新版修复了
