### ISSUE TITLE
创建项目报错 API rate limit

### ISSUE THREAD

**Issue by shenguanjiejie** [kuaifan/eeui#88]
![image](https://user-images.githubusercontent.com/9425605/77528048-36cadb00-6ec8-11ea-9d1c-6be1c72c6e3f.png)

**Comment by kuaifan** [comment]
换个时间再试，好像是网络问题

**Comment by shenguanjiejie** [comment]
今天试也不行, 换成4G网试了一下, 报错是这样的
![image](https://user-images.githubusercontent.com/9425605/77604213-e9448180-6f4c-11ea-97ef-3e84e252460a.png)

**Comment by shenguanjiejie** [comment]
已解决
原因: 我针对GitHub修改了host文件, 把修改去掉或者更新即可.
Mac host文件目录: /etc/hosts
