### ISSUE TITLE
input组件问题

### ISSUE THREAD

**Issue by reimal** [kuaifan/eeui#94]
statusBarType: 'immersion',时
input组件收起键盘、点击完成、点击其他区域等，无法失焦

**Comment by kuaifan** [comment]
immersion采用的是windowIsTranslucent，android就是这样，windowIsTranslucent对键盘不友好，目前没有找到解决方案，建议才用正常页面模式。（如果有高手有解决方案欢迎提交pr）

**Comment by reimal** [comment]
悲剧~~~

**Comment by kang558** [comment]
代码手动给他失去焦点啊
